import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// Repris de fragment-sample-plugin : une seule entrée, la page.

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// La page : l'hôte sert `fragment` (et l'alias `obsidian`) par son shim require,
// et passe tout autre nom au require de Node. Rien de tout ça ne s'embarque.
const page = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"fragment",
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
		// Les modules Node importés avec le préfixe `node:` (codex/ : node:child_process,
		// node:readline, node:process) ne matchent pas la liste `builtin-modules` (noms
		// nus). L'hôte les résout via son shim require à l'exécution → externes aussi.
		...builtins.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// React (îlot de la lueur, ui/lueur.ts) choisit sa version par NODE_ENV : sans lui, les deux s'embarquent.
	define: { "process.env.NODE_ENV": prod ? '"production"' : '"development"' },
});

if (prod) {
	await page.rebuild();
	process.exit(0);
} else {
	await page.watch();
}
