import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// Repris de fragment-sample-plugin, plus une seconde entrée : le processus de
// l'agent (src/serveur/), que le plugin lance à part et qui seul parle à OpenAI.

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// La page : l'hôte sert `fragment` (et l'alias `obsidian`) par son shim require,
// et passe tout autre nom au require de Node. Rien de tout ça ne s'embarque.
const page = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"fragment",
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

// Le processus de l'agent : du Node pur, lancé par child_process.fork.
const serveur = await esbuild.context({
	entryPoints: ["src/serveur/agent-serveur.ts"],
	bundle: true,
	platform: "node",
	format: "cjs",
	target: "node24",
	logLevel: "info",
	minify: true,
	outfile: "agent-serveur.js",
});

if (prod) {
	await page.rebuild();
	await serveur.rebuild();
	process.exit(0);
} else {
	await page.watch();
	await serveur.watch();
}
